"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import PageFrame from "@/components/PageFrame";
import CartSummary from "@/components/CartSummary";
import EmptyState from "@/components/EmptyState";
import { useAppStore } from "@/store/AppStore";

type FormValues = { name: string; mobile: string; email: string; address: string; city: string; deliveryMethod: string; payment: string; notes: string };
const initialValues: FormValues = { name: "", mobile: "", email: "", address: "", city: "", deliveryMethod: "Standard delivery (1-2 days)", payment: "Cash on Delivery", notes: "" };

export default function CheckoutPage() {
  const router = useRouter(); const { cart, hydrated, placeOrder, user } = useAppStore(); const [values, setValues] = useState<FormValues>({ ...initialValues, name: user?.name ?? "", email: user?.email ?? "", mobile: user?.mobile ?? "", address: user?.address ?? "" }); const [errors, setErrors] = useState<Partial<Record<keyof FormValues, string>>>({});
  if (!hydrated) return <PageFrame><section className="listing-page"><div className="container loading-state">Preparing secure checkout...</div></section></PageFrame>;
  if (!cart.length) return <PageFrame><section className="listing-page"><div className="container"><EmptyState type="cart" title="Your cart is empty" description="Add something lovely before starting checkout." /></div></section></PageFrame>;
  const update = (key: keyof FormValues, value: string) => { setValues((current) => ({ ...current, [key]: value })); if (errors[key]) setErrors((current) => ({ ...current, [key]: "" })); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const next: Partial<Record<keyof FormValues, string>> = {}; (Object.keys(values) as (keyof FormValues)[]).forEach((key) => { if (["name", "mobile", "email", "address", "city"].includes(key) && !values[key].trim()) next[key] = "This field is required."; }); if (values.email && !/^\S+@\S+\.\S+$/.test(values.email)) next.email = "Enter a valid email address."; if (values.mobile && values.mobile.replace(/\D/g, "").length < 9) next.mobile = "Enter a valid mobile number."; if (Object.keys(next).length) { setErrors(next); return; } const order = placeOrder(values); router.push(`/order-success?order=${encodeURIComponent(order.id)}`); };
  return <PageFrame><section className="listing-page checkout-page"><div className="container"><div className="page-heading"><div><span className="eyebrow"><span /> Almost there</span><h1>Complete your order</h1><p>Tell us where to deliver your NovaMart favourites.</p></div></div><form id="checkout-form" className="checkout-layout" onSubmit={submit}><div className="checkout-form-page"><FormSection title="Contact details"><div className="form-row"><Field label="Full name" name="name" value={values.name} error={errors.name} placeholder="e.g. Nadeesha Perera" onChange={update} /><Field label="Mobile number" name="mobile" value={values.mobile} error={errors.mobile} placeholder="07X XXX XXXX" onChange={update} /></div><Field label="Email address" name="email" value={values.email} error={errors.email} placeholder="you@example.com" onChange={update} type="email" /></FormSection><FormSection title="Delivery details"><Field label="Delivery address" name="address" value={values.address} error={errors.address} placeholder="House number, street name" onChange={update} textarea /><div className="form-row"><Field label="City" name="city" value={values.city} error={errors.city} placeholder="Colombo" onChange={update} /><label className="field-label">Delivery method<select value={values.deliveryMethod} onChange={(event) => update("deliveryMethod", event.target.value)}><option>Standard delivery (1-2 days)</option><option>Express delivery (same day)</option></select></label></div><Field label="Order notes (optional)" name="notes" value={values.notes} placeholder="Any instructions for the rider?" onChange={update} textarea /></FormSection><FormSection title="Payment method"><div className="payment-options"><PaymentOption value="Cash on Delivery" selected={values.payment} onChange={(value) => update("payment", value)} description="Pay when your order arrives" /><PaymentOption value="Bank Transfer" selected={values.payment} onChange={(value) => update("payment", value)} description="We&apos;ll share details after ordering" /></div></FormSection></div><CartSummary checkout /></form></div></section></PageFrame>;
}

function FormSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="form-section-page"><h2>{title}</h2>{children}</section>; }
function Field({ label, name, value, error, placeholder, onChange, type = "text", textarea = false }: { label: string; name: keyof FormValues; value: string; error?: string; placeholder: string; onChange: (name: keyof FormValues, value: string) => void; type?: string; textarea?: boolean }) { return <label className={`field-label ${error ? "has-error" : ""}`}>{label}{textarea ? <textarea name={name} value={value} placeholder={placeholder} rows={3} onChange={(event) => onChange(name, event.target.value)} /> : <input name={name} value={value} type={type} placeholder={placeholder} onChange={(event) => onChange(name, event.target.value)} />}{error && <small>{error}</small>}</label>; }
function PaymentOption({ value, selected, onChange, description }: { value: string; selected: string; onChange: (value: string) => void; description: string }) { return <label className={`payment-option ${selected === value ? "selected" : ""}`}><input type="radio" checked={selected === value} onChange={() => onChange(value)} /><span><b>{value}</b><small>{description}</small></span></label>; }
