"use client";

import Link from "next/link";
import { Eye, Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { AdminPageHeader, EmptyAdmin, StatusBadge } from "@/components/admin/AdminPrimitives";
import { money } from "@/data/catalog";
import { type OrderStatus, useAppStore } from "@/store/AppStore";

const statuses: OrderStatus[] = ["New", "Confirmed", "Preparing", "Dispatched", "Delivered", "Cancelled"];
export default function AdminOrdersPage() {
  const { orders } = useAppStore(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("All statuses"); const [payment, setPayment] = useState("All payments"); const [sort, setSort] = useState("newest");
  const visible = useMemo(() => [...orders].filter((order) => `${order.id} ${order.customerName} ${order.address}`.toLowerCase().includes(search.toLowerCase()) && (status === "All statuses" || order.status === status) && (payment === "All payments" || order.payment === payment)).sort((a, b) => sort === "oldest" ? a.id.localeCompare(b.id) : sort === "highest" ? b.total - a.total : b.id.localeCompare(a.id)), [orders, search, status, payment, sort]);
  return <div className="admin-route"><AdminPageHeader eyebrow="Fulfilment" title="Orders" description="Track every order from confirmation to doorstep." action={<span className="admin-count-chip">{orders.length} total orders</span>} /><div className="admin-filter-bar"><label className="admin-search"><Search size={16} /><input placeholder="Search order, customer or address" value={search} onChange={(event) => setSearch(event.target.value)} /></label><Filter label="Status" value={status} options={["All statuses", ...statuses]} onChange={setStatus} /><Filter label="Payment" value={payment} options={["All payments", "Cash on Delivery", "Bank Transfer"]} onChange={setPayment} /><Filter label="Sort" value={sort} options={["newest", "oldest", "highest"]} onChange={setSort} /></div><div className="admin-panel admin-data-panel"><div className="admin-panel-toolbar"><span>{visible.length} matching orders</span><span className="admin-muted"><SlidersHorizontal size={13} /> Filters update instantly</span></div>{visible.length ? <div className="admin-table-wrap"><table className="admin-table orders-admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Payment</th><th>Total</th><th>Status</th><th /></tr></thead><tbody>{visible.map((order) => <tr key={order.id}><td><Link className="admin-order-link" href={`/admin/orders/${order.id}`}>{order.id}</Link><small>{order.date}</small></td><td><b>{order.customerName}</b><small>{order.address}</small></td><td>{order.items}</td><td>{order.payment}</td><td><b>{money(order.total)}</b></td><td><StatusBadge status={order.status} /></td><td><Link className="admin-icon-link" href={`/admin/orders/${order.id}`}><Eye size={16} /></Link></td></tr>)}</tbody></table></div> : <EmptyAdmin title="No matching orders" text="Try clearing a filter or searching for a different customer." />}</div></div>;
}
function Filter({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="admin-filter">{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
