"use client";

import { BarChart3, Download, FileSpreadsheet, PieChart } from "lucide-react";
import { useMemo, useState } from "react";
import { AdminPageHeader } from "@/components/admin/AdminPrimitives";
import { money } from "@/data/catalog";
import { useAppStore } from "@/store/AppStore";

export default function AdminReportsPage() {
  const { orders, products, users } = useAppStore();
  const [range, setRange] = useState("All time");
  const completed = orders.filter((order) => order.status !== "Cancelled");
  const revenue = completed.reduce((sum, order) => sum + order.total, 0);
  const payments = ["Cash on Delivery", "Bank Transfer"].map((payment) => ({ payment, count: orders.filter((order) => order.payment === payment).length }));
  const categoryBreakdown = [...new Set(products.map((product) => product.category))].map((category) => ({ category, count: products.filter((product) => product.category === category).length }));
  const bars = useMemo(() => [32, 49, 41, 67, 55, 78, 64, 91, 72, 84, 61, 88], []);
  const download = (kind: string) => {
    const rows = kind === "orders" ? [["Order", "Customer", "Date", "Total", "Status"], ...orders.map((order) => [order.id, order.customerName, order.date, order.total, order.status])] : kind === "products" ? [["Product", "SKU", "Category", "Price", "Stock"], ...products.map((product) => [product.name, product.sku ?? "", product.category, product.salePrice ?? product.price, product.stockQuantity ?? 0])] : [["Name", "Email", "Mobile"], ...users.map((user) => [user.name, user.email, user.mobile])];
    const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `novamart-${kind}.csv`; link.click(); URL.revokeObjectURL(link.href);
  };
  return <div className="admin-route"><AdminPageHeader eyebrow="Performance intelligence" title="Reports" description="A clear read on sales, fulfilment and customer demand." action={<label className="admin-report-range">Date range<select value={range} onChange={(event) => setRange(event.target.value)}><option>All time</option><option>Last 30 days</option><option>Last 90 days</option></select></label>} /><div className="admin-report-metrics"><div><span><BarChart3 size={17} /></span><small>Total sales</small><strong>{money(revenue)}</strong></div><div><span><FileSpreadsheet size={17} /></span><small>Average order</small><strong>{money(orders.length ? Math.round(revenue / orders.length) : 0)}</strong></div><div><span><PieChart size={17} /></span><small>Conversion signal</small><strong>4.9%</strong></div></div><div className="admin-report-grid"><section className="admin-panel report-chart-panel"><div className="admin-panel-heading"><div><span className="admin-eyebrow">Sales trend</span><h3>Monthly sales overview</h3></div><span className="comparison-up">↑ 12.8%</span></div><div className="report-bars">{bars.map((height, index) => <div key={index}><span style={{ height: `${height}%` }} /><small>{["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][index]}</small></div>)}</div></section><section className="admin-panel"><div className="admin-panel-heading"><div><span className="admin-eyebrow">Payment mix</span><h3>Payment methods</h3></div></div><div className="report-breakdown">{payments.map((item) => <div key={item.payment}><span className="breakdown-icon">{item.payment.startsWith("Cash") ? "৳" : "↗"}</span><span><b>{item.payment}</b><small>{item.count} orders</small></span><strong>{orders.length ? Math.round((item.count / orders.length) * 100) : 0}%</strong></div>)}</div></section></div><div className="admin-report-grid lower-report-grid"><section className="admin-panel"><div className="admin-panel-heading"><div><span className="admin-eyebrow">Catalogue demand</span><h3>Sales by category</h3></div></div>{categoryBreakdown.map((item) => <div className="category-report-row" key={item.category}><span>{item.category}</span><i><b style={{ width: `${Math.min(100, item.count * 12 + 10)}%` }} /></i><strong>{item.count}</strong></div>)}</section><section className="admin-panel"><div className="admin-panel-heading"><div><span className="admin-eyebrow">Data exports</span><h3>Download reports</h3></div></div><div className="export-list"><button onClick={() => download("orders")}><Download size={16} /><span><b>Orders CSV</b><small>Order history and status</small></span></button><button onClick={() => download("products")}><Download size={16} /><span><b>Products CSV</b><small>Catalogue and stock</small></span></button><button onClick={() => download("customers")}><Download size={16} /><span><b>Customers CSV</b><small>Customer directory</small></span></button></div></section></div></div>;
}
