"use client";

import Link from "next/link";
import { ArrowRight, LogOut, Pencil, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import PageFrame from "@/components/PageFrame";
import { money } from "@/data/catalog";
import { useAppStore } from "@/store/AppStore";

export default function AccountPage() {
  const router = useRouter(); const { user, orders, hydrated, updateProfile, logout } = useAppStore(); const [editing, setEditing] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { if (hydrated && !user) router.replace("/login"); }, [hydrated, user, router]);
  if (!hydrated || !user) return <PageFrame><section className="listing-page"><div className="container loading-state">Checking your account...</div></section></PageFrame>;
  const customerOrders = orders.filter((order) => order.customerName === user.name || order.customerName === "Nadeesha Perera").slice(-3).reverse();
  const save = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); updateProfile({ name: String(form.get("name") || ""), mobile: String(form.get("mobile") || ""), address: String(form.get("address") || "") }); setEditing(false); setSaved(true); window.setTimeout(() => setSaved(false), 2500); };
  return <PageFrame><section className="listing-page account-page"><div className="container"><div className="page-heading"><div><span className="eyebrow"><span /> Your NovaMart space</span><h1>Hello, {user.name.split(" ")[0]}.</h1><p>Keep your details handy and see what is on its way.</p></div><button className="logout-button" onClick={() => { logout(); router.push("/login"); }}><LogOut size={15} /> Log out</button></div>{saved && <div className="saved-message">Your profile has been updated.</div>}<div className="account-layout"><div className="account-main"><section className="account-card profile-card"><div className="card-heading"><div><span className="profile-avatar"><UserRound size={22} /></span><span><small>Customer profile</small><h2>{user.name}</h2></span></div><button className="icon-action" onClick={() => setEditing((value) => !value)} aria-label="Edit profile"><Pencil size={16} /></button></div>{editing ? <form className="account-edit-form" onSubmit={save}><label>Full name<input name="name" defaultValue={user.name} /></label><label>Mobile number<input name="mobile" defaultValue={user.mobile} /></label><label>Delivery address<textarea name="address" defaultValue={user.address ?? ""} rows={3} /></label><div><button className="primary-button" type="submit">Save changes</button><button className="cancel-button" type="button" onClick={() => setEditing(false)}>Cancel</button></div></form> : <div className="contact-details"><div><small>Email</small><strong>{user.email}</strong></div><div><small>Mobile</small><strong>{user.mobile}</strong></div><div><small>Delivery address</small><strong>{user.address || "Add your delivery address"}</strong></div></div>}</section><section className="account-card"><div className="card-heading"><div><small>Recent activity</small><h2>Recent orders</h2></div><Link className="outline-button" href="/orders">View all <ArrowRight size={15} /></Link></div>{customerOrders.length ? customerOrders.map((order) => <div className="account-order-row" key={order.id}><div><span className="order-status"><i /> {order.status}</span><strong>{order.id}</strong><small>{order.date} · {order.items} items</small></div><b>{money(order.total)}</b></div>) : <p className="muted-copy">Your first order will appear here.</p>}</section></div><aside className="account-aside"><div className="account-stat"><span>Total orders</span><strong>{customerOrders.length || 0}</strong><small>Orders placed with NovaMart</small></div><div className="account-stat blue-stat"><span>Delivery promise</span><strong>1-2 days</strong><small>On standard orders over Rs. 5,000</small></div><Link className="primary-button" href="/shop">Shop everyday essentials <ArrowRight size={16} /></Link></aside></div></div></section></PageFrame>;
}
