"use client";

import Link from "next/link";
import { ArrowRight, Eye, EyeOff, ShoppingBag } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import PageFrame from "@/components/PageFrame";
import { useAppStore } from "@/store/AppStore";

export default function RegisterPage() {
  const router = useRouter(); const { register, user, hydrated } = useAppStore(); const [showPassword, setShowPassword] = useState(false); const [showConfirm, setShowConfirm] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (hydrated && user) router.replace("/account"); }, [hydrated, user, router]);
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name") || "").trim(); const email = String(form.get("email") || "").trim(); const mobile = String(form.get("mobile") || "").trim(); const password = String(form.get("password") || ""); const confirm = String(form.get("confirm") || ""); const terms = form.get("terms"); if (!name || !email || !mobile || !password || !confirm || !terms) { setError("Please complete every field and accept the terms."); return; } if (!/^\S+@\S+\.\S+$/.test(email)) { setError("Enter a valid email address."); return; } if (password.length < 6) { setError("Your password must be at least 6 characters."); return; } if (password !== confirm) { setError("Your passwords do not match."); return; } const result = register({ name, email, mobile, password }); if (!result.ok) { setError(result.error ?? "Unable to create your account."); return; } router.push("/account"); };
  return <PageFrame><section className="auth-page register-page"><div className="auth-card auth-card-wide"><div className="auth-brand"><span className="brand-mark"><ShoppingBag size={22} /></span><span><strong>Nova<span>Mart</span></strong><small>Everything you need, delivered</small></span></div><span className="eyebrow"><span /> Join NovaMart</span><h1>Make everyday easier.</h1><p>Create an account to keep your details and orders in one place.</p><form onSubmit={submit} className="auth-form"><div className="form-row"><label>Full name<input name="name" placeholder="e.g. Nadeesha Perera" /></label><label>Mobile number<input name="mobile" placeholder="07X XXX XXXX" /></label></div><label>Email address<input name="email" type="email" placeholder="you@example.com" /></label><label>Password<span className="password-field"><input name="password" type={showPassword ? "text" : "password"} placeholder="At least 6 characters" /><button type="button" onClick={() => setShowPassword((shown) => !shown)} aria-label="Toggle password visibility">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></span></label><label>Confirm password<span className="password-field"><input name="confirm" type={showConfirm ? "text" : "password"} placeholder="Repeat your password" /><button type="button" onClick={() => setShowConfirm((shown) => !shown)} aria-label="Toggle confirm password visibility">{showConfirm ? <EyeOff size={16} /> : <Eye size={16} />}</button></span></label><label className="terms-check"><input type="checkbox" name="terms" /> <span>I agree to NovaMart&apos;s demo terms and privacy promise.</span></label>{error && <p className="auth-error">{error}</p>}<button className="primary-button auth-submit" type="submit">Create account <ArrowRight size={17} /></button></form><p className="auth-switch">Already have an account? <Link href="/login">Log in</Link></p></div></section></PageFrame>;
}
